"""drop unique constraint on user scheduled date

Revision ID: c7307b15e4de
Revises: 783b65bca023
Create Date: 2026-05-04 17:33:23.644134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7307b15e4de'
down_revision: Union[str, Sequence[str], None] = '783b65bca023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_scheduled_date'), 'schedules', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_user_scheduled_date'), 'schedules', ['user_id', 'scheduled_date'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
